apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: dapr-conf-submit-app-config
spec:
  type: configuration.azure.appconfig
  version: v1
  metadata:
  - name: host
    value: https://appcs-queue-dev-uks-01.azconfig.io
  - name: azureTenantId
    secretKeyRef:
      name: azure-tenant-id
      key: azure-tenant-id
auth:
  secretStore: dapr-conf-submit-key-vault