apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: dapr-conf-submit-key-vault
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName # Required
    value: kv-queue-dev-uks-01    # this is taken from the keyvault bicep file
  - name: azureEnvironment
    value: "AZUREPUBLICCLOUD"