apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: dapr-conf-submit-queue-state
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: outboxPublishPubsub
    value: "trans-outbox-pubsub"
  - name: outboxPublishTopic
    value: "trans-outbox-pubsub-topic"