apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: dapr-conf-submit-queue-state
spec:
  type: state.azure.cosmosdb
  version: v1
  metadata:
  - name: url
    secretKeyRef:
      name: cosmos-db-account-uri
      key: cosmos-db-account-uri
  - name: database
    value: cosmos-queue-state-dev-uks-01
  - name: collection
    value: cosco-queue-requests-dev-uks-01
  - name: outboxPublishPubsub
    value: dapr-conf-submit-queue-transoutbox-pubsub
  - name: outboxPublishTopic
    value: sbt-request-submission-dev-uks-01
  - name: outboxPubsub
    value: 'cosmos-queue-state-dev-uks-01'
  - name: outboxDiscardWhenMissingState
    value: false
auth:
  secretStore: dapr-conf-submit-key-vault